version: "3.8"
services:
       nasa:
           container_name: nasa
           image: nasa
           restart: always
           build: .
           ports:
             - "8080:8080"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data/db:/data/db
             ports:
               - '27017:27017'